### ISSUE TITLE
I have been unable to create a new react app using npx create-react-app. I am getting this error:

### ISSUE THREAD

**Issue by BigDreamDev** [BigDreamDev/Betting-Dashboard-Front#6]
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at process.cwd (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at new Config (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:92:19)
    at new <anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:83:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:71:30)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}

**Comment by funnynight** [comment]
Create a folder with your app name then run npx create-react-app folderName
